import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('.test-output',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/');
await page.getByRole('button',{name:'교사 화면',exact:true}).click();
await page.getByRole('heading',{name:'교실 현황',exact:true}).waitFor();
await page.screenshot({path:'.test-output/teacher-dashboard.png',fullPage:true});
await page.locator('nav').getByRole('button',{name:/문제 검토/}).click();
await page.getByRole('button',{name:'승인 + 창조력 지급',exact:true}).waitFor();
await page.getByRole('button',{name:'승인 + 창조력 지급',exact:true}).click();
assert.match(await page.getByRole('status').textContent(),/미리보기/);
await page.getByRole('button',{name:'세계 관리',exact:true}).click();
await page.getByRole('img',{name:'우리 반 공동 세계 지도'}).waitFor();
await page.locator('nav').getByRole('button',{name:'창작 검토',exact:true}).click();
await page.getByLabel('우수 창작 추가 창조력').fill('5');
await page.getByRole('button',{name:'승인 및 생성 · 추가 +5'}).waitFor();
await page.getByRole('button',{name:'새로고침',exact:true}).last().click();
await page.getByRole('button',{name:'나가기'}).click();
await page.getByRole('button',{name:'학생 화면',exact:true}).click();
assert.equal(await page.getByText('빠른 행동',{exact:true}).count(),0);
await page.getByRole('button',{name:'가방',exact:true}).click();
await page.getByText('아직 아이템이 없습니다.',{exact:true}).waitFor();
await page.getByRole('button',{name:'도움말',exact:true}).click();
await page.getByRole('button',{name:'터미널 전체화면'}).click();
assert.equal(await page.locator('.ps-fullscreen').count(),1);
await page.screenshot({path:'.test-output/terminal-fullscreen.png',fullPage:true});
await page.keyboard.press('Escape');
assert.equal(await page.locator('.ps-fullscreen').count(),0);
await page.locator('nav').getByRole('button',{name:'창작 작업실',exact:true}).click();
for(const kind of ['npc','book','item','monster','skill']){
 await page.getByLabel('만들 것',{exact:true}).selectOption(kind);
 for(const label of ['칸 수','장소 성격','연결할 기존 장소','확장 방향'])assert.equal(await page.getByLabel(label,{exact:true}).isDisabled(),true,kind+' map fields disabled');
 assert.equal(await page.getByLabel('공격력',{exact:true}).count(),['item','monster'].includes(kind)?1:0);
 assert.equal(await page.getByLabel('효과',{exact:true}).count(),['item','monster','skill'].includes(kind)?1:0);
}
await page.getByLabel('만들 것',{exact:true}).selectOption('item');
await page.getByLabel('공격력',{exact:true}).fill('10');
await page.getByLabel('효과',{exact:true}).selectOption('heal');
await page.getByLabel('효과 강도',{exact:true}).fill('5');
await page.screenshot({path:'.test-output/creation-item.png',fullPage:true});
await page.getByLabel('만들 것',{exact:true}).selectOption('map');
assert.equal(await page.getByLabel('장소 성격',{exact:true}).locator('option[value="boss"]').count(),0);
await page.getByLabel('장소 성격',{exact:true}).selectOption('library');
await page.getByLabel('연계 마을').waitFor();
assert.equal(await page.getByLabel('확장 방향',{exact:true}).isDisabled(),true);
await page.getByRole('button',{name:'문제 만들기',exact:true}).click();
assert.equal(await page.getByLabel('문제유형',{exact:true}).locator('option').count(),3);
await page.getByLabel('문제유형',{exact:true}).selectOption('choice');
for(let i=1;i<=4;i++)await page.getByLabel(`보기 ${i}`,{exact:true}).fill(`보기 ${i}`);
assert.equal(await page.locator('.choices-input input').count(),4);
await page.getByLabel('문제',{exact:true}).fill('물의 상태는 무엇인가요?');
await page.getByLabel('해설',{exact:true}).fill('물은 세 가지 상태로 존재합니다.');
await page.getByLabel('정답',{exact:true}).selectOption('4');
await page.screenshot({path:'.test-output/student-question.png',fullPage:true});
await page.getByLabel('문제유형',{exact:true}).selectOption('short');
assert.equal(await page.locator('.choices-input').count(),0);
await page.getByLabel('정답',{exact:true}).fill('물');
await page.getByRole('button',{name:'교사에게 제출',exact:true}).click();
assert.match(await page.getByRole('status').textContent(),/미리보기/);
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'.test-output/mobile-question.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile must not overflow horizontally');
await page.locator('nav').getByRole('button',{name:'세계 탐험',exact:true}).click();
await page.locator('#mud-command').fill('가방');
await page.locator('.ps-command button').click();
await page.getByText('아직 아이템이 없습니다.',{exact:true}).waitFor();
const input=await page.locator('#mud-command').boundingBox(),button=await page.locator('.ps-command button').boundingBox();
assert.ok(Math.abs(input.y+input.height/2-button.y-button.height/2)<3,'command and button remain on one line');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'terminal fits mobile');
await page.screenshot({path:'.test-output/mobile-terminal.png',fullPage:true});
assert.deepEqual(errors,[]);
await browser.close();
console.log('Browser checks passed: teacher preview, approval guard, map, OX/short/four-choice forms, mobile layout, no runtime errors.');
