import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('.test-output',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/');
await page.getByRole('button',{name:'교사 화면',exact:true}).click();
await page.getByRole('heading',{name:'교실 현황',exact:true}).waitFor();
await page.screenshot({path:'.test-output/teacher-dashboard.png',fullPage:true});
await page.locator('nav').getByRole('button',{name:/문제 검토/}).click();
await page.getByRole('button',{name:'승인 + 창조력 지급',exact:true}).waitFor();
await page.getByRole('button',{name:'승인 + 창조력 지급',exact:true}).click();
assert.match(await page.getByRole('status').textContent(),/미리보기/);
await page.getByRole('button',{name:'세계 관리',exact:true}).click();
await page.getByRole('img',{name:'우리 반 공동 세계 지도'}).waitFor();
await page.getByRole('button',{name:'나가기'}).click();
await page.getByRole('button',{name:'학생 화면',exact:true}).click();
await page.getByRole('button',{name:'문제 만들기',exact:true}).click();
assert.equal(await page.getByLabel('문제유형',{exact:true}).locator('option').count(),3);
await page.getByLabel('문제유형',{exact:true}).selectOption('choice');
for(let i=1;i<=4;i++)await page.getByLabel(`보기 ${i}`,{exact:true}).fill(`보기 ${i}`);
assert.equal(await page.locator('.choices-input input').count(),4);
await page.getByLabel('문제',{exact:true}).fill('물의 상태는 무엇인가요?');
await page.getByLabel('해설',{exact:true}).fill('물은 세 가지 상태로 존재합니다.');
await page.getByLabel('정답',{exact:true}).selectOption('4');
await page.screenshot({path:'.test-output/student-question.png',fullPage:true});
await page.getByLabel('문제유형',{exact:true}).selectOption('short');
assert.equal(await page.locator('.choices-input').count(),0);
await page.getByLabel('정답',{exact:true}).fill('물');
await page.getByRole('button',{name:'교사에게 제출',exact:true}).click();
assert.match(await page.getByRole('status').textContent(),/미리보기/);
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'.test-output/mobile-question.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile must not overflow horizontally');
assert.deepEqual(errors,[]);
await browser.close();
console.log('Browser checks passed: teacher preview, approval guard, map, OX/short/four-choice forms, mobile layout, no runtime errors.');
