import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { BookOpen, Compass, Hammer, ShieldCheck, Sparkles, Users, LogOut, RefreshCw, Map, Settings as SettingsIcon, ChevronRight } from 'lucide-react';
import { rpc, snapshot, studentAccess, supabase } from './api';
import { categories, defaults, estimate, labels, previewSnapshot, validateQuestion, type Question, type Settings, type Snapshot } from './model';
import Proposals from './CreationWorkshop';
import Adventure from './AdventureTerminal';
import StudentShell from './StudentShell';
import StudentManagement from './StudentManagement';
import './classroom.css';
import './adventure.css';
import './terminal-shell.css';

type Run = (action:()=>Promise<unknown>,message?:string)=>Promise<void>;
const status=(s:string)=><span className={`tag ${s}`}>{labels[s]||s}</span>;
const formData=(e:FormEvent<HTMLFormElement>)=>new FormData(e.currentTarget);
function Check({id,selected,set}:{id:string;selected:string[];set:(v:string[])=>void}) {return <input type="checkbox" aria-label="선택" checked={selected.includes(id)} onChange={e=>set(e.target.checked?[...selected,id]:selected.filter(x=>x!==id))}/>;}
function Empty({children}:{children:ReactNode}) {return <div className="empty">{children}</div>;}

export default function ClassroomApp() {
 const [data,setData]=useState<Snapshot|null>(null),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('home');
 async function refresh(){const next=await snapshot();setData(next);}
 const run:Run=async(action,message='저장했습니다.')=>{if(preview){setNotice('화면 미리보기입니다. 실제 저장과 승인은 Supabase 연결 후 사용할 수 있습니다.');return;}setBusy(true);setError('');setNotice('');try{await action();await refresh();setNotice(message);}catch(e){setError((e as Error).message||'처리하지 못했습니다.');}finally{setBusy(false);}};
 useEffect(()=>{if(!supabase)return;setBusy(true);refresh().catch(e=>setError(e.message)).finally(()=>setBusy(false));const {data:listener}=supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')setData(null);});return()=>listener.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!data||preview)return;const check=()=>{if(document.visibilityState==='visible')refresh().catch(e=>{setData(null);setError(e.message);});};window.addEventListener('focus',check);return()=>window.removeEventListener('focus',check);},[data?.profile.id,preview]);
 const teacher=data?.profile.role==='teacher';
 const leave=async()=>{if(!preview){const result=await supabase?.auth.signOut();if(result?.error)throw result.error;}setPreview(false);setData(null);setTab('home');setError('');setNotice('');};
 if(data&&!teacher)return <StudentShell data={data} run={run} preview={preview} busy={busy} error={error} notice={notice} onLeave={leave} renderPanel={panel=>panel==='questions'?<Questions data={data} run={run}/>:panel==='proposals'?<Proposals data={data} run={run} teacher={false}/>:<Wallet data={data} run={run}/>}/>;
 const menus=teacher?[['home','교실 현황',Compass],['students','학생 관리',Users],['questions','문제 검토',BookOpen],['proposals','창작 검토',Hammer],['world','세계 관리',Map],['settings','운영 설정',SettingsIcon]]:[['home','세계 탐험',Compass],['questions','문제 만들기',BookOpen],['proposals','창작 작업실',Hammer],['wallet','창조력 · 성장',Sparkles]];
 return <div className="classroom">
 <aside className="rail"><div className="brand"><img className="brand-icon" src="/mud-icon.png" alt="책과 성 모양의 우리 반 MUD 아이콘"/><div>우리 반 MUD<small>LEARN · CREATE · EXPLORE</small></div></div>
 <div className="rail-caption">{data?(teacher?'TEACHER CONSOLE':'CLASSROOM ADVENTURE'):'함께 만드는 배움의 세계'}</div>
 {data&&<nav>{menus.map(([id,name,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/>{name}{id==='questions'&&teacher&&<b>{data.questions.filter(q=>q.status==='submitted').length}</b>}</button>)}</nav>}
 <div className="rail-bottom"><span className="online-dot"/> {preview?'읽기 전용 미리보기':supabase?'학급 전용 공간':'연결 준비 중'}<small>작은 질문이 새로운 세계를 만듭니다.</small></div></aside>
 <main><header className="topbar"><span>{teacher?'교사 관리실':'배움의 모험'}</span><div>{data&&<><span>{data.profile.nickname}</span><button aria-label="새로고침" disabled={busy} onClick={()=>run(async()=>{},'새로고침했습니다.')}><RefreshCw size={16}/></button><button onClick={async()=>{if(!preview)await supabase?.auth.signOut();setPreview(false);setData(null);setTab('home');}}><LogOut size={16}/>나가기</button></>}</div></header>
 <div className="page">{preview&&<div className="banner">미리보기 · 예시 데이터이며 저장하거나 실제 보상을 지급하지 않습니다.</div>}
 {error&&<div role="alert" className="alert">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
 <fieldset disabled={busy} className="workspace">{!data?<Login run={run} onPreview={role=>{setPreview(true);setData(previewSnapshot(role));setError('');setTab('home');}}/>:<>
 <div className="page-heading"><div><span className="eyebrow">{teacher?'함께 자라는 교실':'오늘도 한 칸 더, 새로운 발견'}</span><h1>{menus.find(m=>m[0]===tab)?.[1] as string}</h1><p>{teacher?'검토는 간단하게, 학생들의 창작은 더 넓게.':'문제를 만들고, 창조력을 모아 우리 반의 세계를 넓혀 보세요.'}</p></div><span className="role-badge">{teacher?<ShieldCheck size={18}/>:<Sparkles size={18}/>} {teacher?'교사 관리자':`창조력 ${data.profile.balance-data.profile.reserved}`}</span></div>
 {teacher&&tab==='home'&&<Dashboard data={data} go={setTab}/>}
 {teacher&&tab==='students'&&<Students data={data} run={run}/>}
 {tab==='questions'&&(teacher?<ReviewQuestions data={data} run={run}/>:<Questions data={data} run={run}/>)}
 {tab==='proposals'&&<Proposals data={data} run={run} teacher={!!teacher}/>}
 {teacher&&tab==='world'&&<World data={data} run={run}/>}
 {teacher&&tab==='settings'&&<SettingsForm settings={data.settings} run={run}/>}
 {!teacher&&tab==='home'&&<Adventure data={data} run={run} preview={preview}/>}
 {!teacher&&tab==='wallet'&&<Wallet data={data} run={run}/>}
 </>}</fieldset>{busy&&<div className="working" role="status">처리 중…</div>}</div>
 </main></div>;
}

function Login({run,onPreview}:{run:Run;onPreview:(r:'teacher'|'student')=>void}) {
 const [mode,setMode]=useState('login');
 return <div className="login-layout"><section className="welcome"><span className="eyebrow">OUR CLASS, OUR WORLD</span><h1>질문 하나로<br/>새로운 세계가<br/><em>열립니다.</em></h1><p>문제를 풀고, 친구의 질문을 만나고,<br/>함께 다음 모험을 만들어 보세요.</p><div className="pixel-world">⌂ ── ✦ ── ♜<br/>　　│　　 │<br/>　　♧ ── ◇</div></section><section className="card login-card"><h2>{mode==='teacher'?'교사 관리실':'모험을 시작할까요?'}</h2><p>우리 학급만 사용하는 작은 세계</p><div className="segmented">{[['login','학생 로그인'],['signup','가입 신청'],['teacher','교사']].map(([id,text])=><button key={id} className={mode===id?'chosen':''} onClick={()=>setMode(id)}>{text}</button>)}</div>
 <form onSubmit={e=>{e.preventDefault();const f=formData(e);run(async()=>{if(mode==='teacher'){if(!supabase)throw new Error('Supabase 연결이 필요합니다.');const {error}=await supabase.auth.signInWithPassword({email:String(f.get('name')),password:String(f.get('password'))});if(error)throw error;}else await studentAccess(mode,String(f.get('name')),String(f.get('password')));},mode==='signup'?'가입 신청을 보냈습니다. 선생님 승인 후 로그인해 주세요.':'로그인했습니다.');}}>
 <label>{mode==='teacher'?'교사 이메일':'닉네임'}<input key={mode} name="name" required type={mode==='teacher'?'email':'text'} maxLength={mode==='teacher'?200:20} placeholder={mode==='teacher'?'teacher@example.com':'사용할 닉네임'}/></label>
 <label>{mode==='teacher'?'비밀번호':'PIN 번호'}<input name="password" key={`${mode}-pin`} required type="password" inputMode={mode==='teacher'?'text':'numeric'} pattern={mode==='teacher'?undefined:'[0-9]{6}'} minLength={mode==='teacher'?8:6} maxLength={mode==='teacher'?100:6} placeholder={mode==='teacher'?'교사 비밀번호':'숫자 6자리'}/></label>
 <button className="primary wide" type="submit">{mode==='signup'?'선생님께 가입 신청':'입장하기'}<ChevronRight size={17}/></button></form>
 <small>{mode==='signup'?'선생님이 승인한 뒤 이용할 수 있어요. 이메일은 필요 없어요.':'PIN을 잊었다면 선생님께 초기화를 요청하세요.'}</small>
 <div className="preview-links"><span>연결 전 화면 살펴보기</span><button onClick={()=>onPreview('teacher')}>교사 화면</button><button onClick={()=>onPreview('student')}>학생 화면</button></div></section></div>;
}

function Dashboard({data,go}:{data:Snapshot;go:(t:string)=>void}) {
 const metrics=[['가입 승인 대기',data.students.filter(s=>s.status==='pending').length,'students'],['문제 검토 대기',data.questions.filter(q=>q.status==='submitted').length,'questions'],['창작 승인 대기',data.proposals.filter(p=>p.status==='pending').length,'proposals'],['우리 세계의 장소',data.places.filter(p=>p.active).length,'world']];
 return <><div className="metrics">{metrics.map(([label,n,tab])=><button className="card metric" key={label} onClick={()=>go(String(tab))}><span>{label}</span><strong>{n}<small>개</small></strong><span className="metric-link">살펴보기 →</span></button>)}</div><div className="dashboard-stack"><section className="card"><h2>오늘의 검토함</h2><p>질문이 새로운 모험의 시작이 됩니다.</p>{data.questions.filter(q=>q.status==='submitted').slice(0,4).map(q=><button className="review-row" key={q.id} onClick={()=>go('questions')}><span className="subject-icon">{q.subject[0]}</span><div><strong>{q.body}</strong><small>{data.students.find(s=>s.id===q.author)?.nickname||(q.author?"학생":"기본 문제")} · {q.subject} · {labels[q.kind]}</small></div><ChevronRight size={17}/></button>)}{!data.questions.some(q=>q.status==='submitted')&&<Empty>검토할 문제가 없습니다.</Empty>}</section><section className="card"><h2>세계가 자라고 있어요</h2><MiniMap data={data}/><p>맵 한 칸 {data.settings.room_cost} · 문제 승인 {data.settings.question_reward} 창조력</p><button className="secondary" onClick={()=>go('world')}>전체 세계 관리</button></section></div></>;
}

function Questions({data,run}:{data:Snapshot;run:Run}) {
 const blank=()=>({subject:localStorage.getItem('mud_classroom_last_subject')||data.settings.subjects[0],kind:'ox' as Question['kind'],body:'',options:['','','',''],answer:'O',explanation:''});
 const [q,setQ]=useState(blank),[edit,setEdit]=useState<string|null>(null),[done,setDone]=useState(false);
 useEffect(()=>{if(!data.settings.subjects.includes(q.subject))setQ(v=>({...v,subject:data.settings.subjects[0]}));},[data.settings.subjects.join('|')]);
 function set(field:string,value:any){setDone(false);setQ(v=>({...v,[field]:value}));}
 return <div className="two-col form-columns"><section className="card"><h2>{edit?'문제 수정하기':'내가 만드는 한 문제'}</h2><p>배운 내용을 친구에게 설명해 보세요.</p><form onSubmit={e=>{e.preventDefault();const payload={...q,options:q.kind==='choice'?q.options:[]};run(async()=>{const invalid=validateQuestion(payload);if(invalid)throw new Error(invalid);await rpc('submit_question',{p_id:edit,p_subject:q.subject,p_kind:q.kind,p_body:q.body,p_options:payload.options,p_answer:q.answer,p_explanation:q.explanation});localStorage.setItem('mud_classroom_last_subject',q.subject);setDone(true);setEdit(null);},'선생님께 문제를 제출했습니다.');}}>
 <div className="form-row"><label>과목<select aria-label="과목" value={q.subject} onChange={e=>{set('subject',e.target.value);localStorage.setItem('mud_classroom_last_subject',e.target.value);}}>{data.settings.subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>문제유형<select aria-label="문제유형" value={q.kind} onChange={e=>{const kind=e.target.value as Question['kind'];setQ(v=>({...v,kind,answer:kind==='ox'?'O':kind==='choice'?'1':''}));setDone(false);}}><option value="ox">OX</option><option value="short">단답형</option><option value="choice">객관식 · 4지선다</option></select></label></div>
 <label>문제<textarea required minLength={3} maxLength={2000} rows={4} value={q.body} onChange={e=>set('body',e.target.value)} placeholder="친구에게 어떤 질문을 하고 싶나요?"/></label>
 {q.kind==='choice'&&<div className="choices-input">{q.options.map((o,i)=><label key={i}>보기 {i+1}<input required maxLength={500} value={o} onChange={e=>set('options',q.options.map((x,j)=>i===j?e.target.value:x))}/></label>)}</div>}
 <label>정답{q.kind==='short'?<input required maxLength={200} value={q.answer} onChange={e=>set('answer',e.target.value)} placeholder="짧은 정답 하나"/>:<select aria-label="정답" value={q.answer} onChange={e=>set('answer',e.target.value)}>{(q.kind==='ox'?['O','X']:['1','2','3','4']).map(a=><option key={a} value={a}>{q.kind==='choice'?`${a}번`:a}</option>)}</select>}</label>
 <label>해설<textarea required maxLength={2000} rows={3} value={q.explanation} onChange={e=>set('explanation',e.target.value)} placeholder="왜 이 답이 맞는지 짧게 설명해 주세요."/></label>
 <button type="submit" className="primary wide" disabled={done}>교사에게 제출</button>{done&&<button type="button" className="secondary wide" onClick={()=>{setQ({...blank(),subject:q.subject});setDone(false);}}>같은 과목으로 다음 문제 만들기</button>}</form></section>
 <section className="card"><h2>내가 보낸 문제</h2><p>최초 승인 시 최대 {data.settings.question_reward} 창조력 · 하루 {data.settings.daily_reward_cap}까지</p>{data.questions.length===0&&<Empty>첫 문제를 만들어 보세요.</Empty>}{data.questions.map(row=><article className="list-card" key={row.id}><div className="row-between">{status(row.status)}<small>{row.subject} · {labels[row.kind]}</small></div><h3>{row.body}</h3>{row.feedback&&<p className="feedback">선생님: {row.feedback}</p>}<button className="text-button" onClick={()=>{setQ({subject:row.subject,kind:row.kind,body:row.body,options:row.kind==='choice'?row.options:['','','',''],answer:row.answer,explanation:row.explanation});setEdit(row.id);setDone(false);}}>수정하기{row.rewarded?' · 추가 보상 없음':''}</button></article>)}</section></div>;
}

function ReviewQuestions({data,run}:{data:Snapshot;run:Run}) {
 const [bonus,setBonus]=useState(0);
 const [selected,setSelected]=useState<string[]>([]),[filter,setFilter]=useState('submitted'),[search,setSearch]=useState(''),[feedback,setFeedback]=useState(''),[accepted,setAccepted]=useState<Record<string,string>>({});
 const rows=data.questions.filter(q=>(filter==='all'||q.status===filter)&&`${q.body} ${q.subject} ${data.students.find(s=>s.id===q.author)?.nickname||(q.author?"학생":"기본 문제")}`.includes(search));
 const eligible=selected.filter(id=>data.questions.some(q=>q.id===id&&q.status==='submitted'));
 const review=(ids:string[],action:string)=>run(async()=>{await rpc('review_questions',{p_ids:ids,p_action:action,p_feedback:feedback,p_bonus:action==='approved'?bonus:0,p_accepted:ids.length===1?(accepted[ids[0]]||'').split(',').map(x=>x.trim()).filter(Boolean):[]});setSelected([]);},action==='approved'?'승인과 창조력 지급을 처리했습니다.':'검토 결과를 보냈습니다.');
 return <><div className="toolbar card"><input aria-label="문제 검색" placeholder="문제 · 과목 · 학생 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="검토 상태" value={filter} onChange={e=>{setFilter(e.target.value);setSelected([]);}}>{['submitted','approved','revision','rejected','all'].map(s=><option key={s} value={s}>{labels[s]||'전체'}</option>)}</select><button onClick={()=>setSelected(rows.filter(q=>q.status==='submitted').map(q=>q.id))}>대기 문제 모두 선택</button></div>
 <div className="approval-bar"><span>{eligible.length}개 선택 · 최대 {eligible.filter(id=>!data.questions.find(q=>q.id===id)?.rewarded).length*data.settings.question_reward+eligible.length*bonus} 창조력 <small>(학생별 일일 한도 적용)</small></span><button className="primary" disabled={!eligible.length} onClick={()=>review(eligible,'approved')}>선택 승인 + 창조력 지급</button></div>
 <label className="feedback-input">우수 문제 추가 창조력 (문제당)<input type="number" min={0} max={100} value={bonus} onChange={e=>setBonus(Number(e.target.value))}/><small>선택 승인 시 각 문제에 적용 · 같은 문제의 추가 보상은 한 번만 지급</small></label><label className="feedback-input">검토 의견<input value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="수정할 내용을 짧게 남겨 주세요."/></label>
 {!rows.length&&<Empty>이 상태의 문제가 없습니다.</Empty>}<div className="review-grid">{rows.map(q=><article className="card question-review" key={q.id}><div className="row-between"><div className="inline"><Check id={q.id} selected={selected} set={setSelected}/><strong>{data.students.find(s=>s.id===q.author)?.nickname||(q.author?"학생":"기본 문제")}</strong></div>{status(q.status)}</div><div className="chips"><span>{q.subject}</span><span>{labels[q.kind]}</span><span>{q.rewarded?'지급 완료':`최대 +${data.settings.question_reward}`}</span></div><h3>{q.body}</h3>{q.options.map((o,i)=><div key={i} className={q.answer===String(i+1)?'answer correct':'answer'}>{i+1}. {o}</div>)}<div className="answer-key">정답: {q.answer}</div><p className="explanation">{q.explanation}</p>{q.kind==='short'&&<label>추가 인정 정답 <small>쉼표로 구분 · 개별 승인 시 적용</small><input value={accepted[q.id]||''} onChange={e=>setAccepted({...accepted,[q.id]:e.target.value})}/></label>}
 {data.questions.some(other=>other.id!==q.id&&other.body.replace(/\s/g,'')===q.body.replace(/\s/g,''))&&<p className="warning">같은 문장의 문제가 있습니다. 중복 여부를 확인해 주세요.</p>}
 {q.status==='submitted'&&<div className="actions"><button className="primary" onClick={()=>review([q.id],'approved')}>승인 + 창조력 지급</button><button onClick={()=>review([q.id],'revision')}>수정 요청</button><button onClick={()=>review([q.id],'rejected')}>반려</button></div>}{q.status==='approved'&&<button onClick={()=>run(()=>rpc('set_active',{p_kind:'question',p_ids:[q.id],p_active:false}),'출제를 중지했습니다. 기존 보상은 유지됩니다.')}>출제 중지</button>}</article>)}</div></>;
}

function Students({data,run}:{data:Snapshot;run:Run}) {return <><StudentManagement data={data} run={run}/><section className="card"><h2>최근 창조력 내역</h2><LedgerList data={data}/></section></>;}
function MiniMap({data,onSelect}:{data:Snapshot;onSelect?:(id:string)=>void}) {
 const mapPlaces=data.places.filter(p=>!p.village_id);
 const xs=mapPlaces.map(p=>p.x),ys=mapPlaces.map(p=>p.y),minX=Math.min(0,...xs),minY=Math.min(0,...ys);
 const pos=(id:string)=>{const p=data.places.find(p=>p.id===id);return p?[(p.x-minX)*160+95,(p.y-minY)*110+55]:[0,0];};
 return <div className="map-scroll"><svg role="img" aria-label="우리 반 공동 세계 지도" width={Math.max(500,(Math.max(0,...xs)-minX+1)*160+30)} height={Math.max(220,(Math.max(0,...ys)-minY+1)*110+30)}>{data.links.map(l=>{const a=pos(l.source),b=pos(l.target);return <line key={`${l.source}-${l.direction}`} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke="#9aada6" strokeWidth="2"/>;})}{mapPlaces.map(p=>{const [x,y]=pos(p.id);return <g key={p.id} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={p.name} onClick={()=>onSelect?.(p.id)} onKeyDown={e=>{if(e.key==='Enter')onSelect?.(p.id);}} style={{cursor:onSelect?'pointer':'default'}} opacity={p.active?1:.4}><rect x={x-68} y={y-30} width="136" height="64" rx="12" fill={p.category==='square'?'#245e4b':'#fff'} stroke="#b5c8bd"/><text x={x} y={y-5} textAnchor="middle" fill={p.category==='square'?'#fff':'#263d34'} fontSize="12">{p.name.length>11?p.name.slice(0,10)+'…':p.name}</text><text x={x} y={y+15} textAnchor="middle" fill={p.category==='square'?'#d0e7d9':'#70847a'} fontSize="10">{categories[p.category]}</text></g>;})}</svg></div>;
}

function World({data,run}:{data:Snapshot;run:Run}) {
 const [kind,setKind]=useState('place'),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[place,setPlace]=useState('');
 const rows=(kind==='place'?data.places:data.entities.filter(e=>e.kind===kind)).filter(e=>e.name.includes(search));
 return <><section className="card"><div className="row-between"><h2>공동 세계 지도</h2><small>장소를 누르면 상세 정보를 볼 수 있습니다.</small></div><MiniMap data={data} onSelect={setPlace}/>{place&&<div className="feedback"><strong>{data.places.find(p=>p.id===place)?.name}</strong><p>{data.places.find(p=>p.id===place)?.description}</p><small>출구: {data.links.filter(l=>l.source===place).map(l=>`${l.direction} → ${data.places.find(p=>p.id===l.target)?.name}`).join(' / ')||'없음'}</small></div>}</section>
 <div className="toolbar card"><select aria-label="콘텐츠 종류" value={kind} onChange={e=>{setKind(e.target.value);setSelected([]);}}><option value="place">전체 맵</option>{['monster','item','skill','npc','book'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select><input placeholder="이름 검색" aria-label="콘텐츠 검색" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>setSelected(rows.map(r=>r.id))}>전체 선택</button><button disabled={!selected.length} onClick={()=>run(()=>rpc('set_active',{p_kind:kind,p_ids:selected,p_active:true}))}>활성화</button><button disabled={!selected.length} onClick={()=>run(()=>rpc('set_active',{p_kind:kind,p_ids:selected,p_active:false}),'비활성화했습니다. 해당 장소의 학생은 광장으로 이동합니다.')}>비활성화</button></div>
 <div className="card table-wrap"><table><thead><tr><th>선택</th><th>이름</th><th>종류 / 능력</th><th>제작자</th><th>상태</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><Check id={r.id} selected={selected} set={setSelected}/></td><td>{r.name}</td><td>{r.category?categories[r.category]:r.kind==='monster'?`HP ${r.data.hp} / ATK ${r.data.attack} / DEF ${r.data.defense}`:`${labels[r.kind]} · ${r.data.description||labels[r.data.effect]||""}`}</td><td>{data.students.find(s=>s.id===r.creator)?.nickname||'교사'}</td><td>{r.active?'활성':'중지'}</td></tr>)}</tbody></table>{rows.length===0&&<Empty>등록된 콘텐츠가 없습니다.</Empty>}</div>
 {selected.length>0&&<ContentEditor kind={kind} ids={selected} data={data} run={run}/>}</>;
}

function ContentEditor({kind,ids,data,run}:{kind:string;ids:string[];data:Snapshot;run:Run}) {
 const [field,setField]=useState('name'),[value,setValue]=useState('');
 useEffect(()=>{setField(ids.length===1?'name':kind==='place'||['npc','book'].includes(kind)?'description':kind==='monster'?'attack':'power');setValue('');},[kind,ids.join(',')]);
 const fields:Record<string,string>={...(ids.length===1?{name:'이름'}:{}),description:'설명',...(kind==='place'?{category:'장소 성격'}:kind==='monster'?{hp:'체력',attack:'공격력',defense:'방어력',level:'레벨',min_correct:'최소 정답 횟수',place:'배치 장소',power:'효과 강도',effect:'효과'}:['npc','book'].includes(kind)?{}:kind==='item'?{hp:'체력',attack:'공격력',defense:'방어력',power:'효과 강도',effect:'효과'}:{power:'효과 강도',effect:'효과'})};
 return <section className="card"><h2>선택한 {ids.length}개 편집</h2><p>수정할 항목 하나를 선택해 적용합니다. 진행 중인 전투는 시작 당시 능력치를 유지합니다.</p><form onSubmit={e=>{e.preventDefault();run(()=>rpc('edit_content',{p_kind:kind,p_ids:ids,p_patch:{[field]:['hp','attack','defense','level','min_correct','power'].includes(field)?Number(value):value}}));}}><div className="form-row"><label>수정할 항목<select value={field} onChange={e=>{setField(e.target.value);setValue('');}}>{Object.entries(fields).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>변경할 값{['category','place','effect'].includes(field)?<select required value={value} onChange={e=>setValue(e.target.value)}><option value="">선택하세요</option>{(field==='category'?Object.entries(categories):field==='place'?data.places.filter(p=>p.active&&['forest','road','dungeon'].includes(p.category)).map(p=>[p.id,p.name]):(kind==='skill'?['heal','guard','strike']:['none','heal','guard','strike']).map(k=>[k,labels[k]])).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>:<input required value={value} onChange={e=>setValue(e.target.value)} type={['hp','attack','defense','level','min_correct','power'].includes(field)?'number':'text'}/>}</label></div><button className="primary">선택 항목에 적용</button></form></section>;
}

function SettingsForm({settings,run}:{settings:Settings;run:Run}) {
 const [s,setS]=useState(settings),[subjects,setSubjects]=useState(settings.subjects.join(', '));
 return <section className="card settings-card"><h2>수업에 맞게 바꾸세요</h2><p>새 규칙은 다음 신청부터 적용됩니다. 이미 예약한 제작 비용은 유지합니다.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{if(!supabase)throw new Error('연결이 필요합니다.');const {error}=await supabase.from('mud_settings').update({...s,subjects:[...new Set(subjects.split(',').map(x=>x.trim()).filter(Boolean))]}).eq('id',true);if(error)throw error;});}}><label>과목 목록 <small>쉼표로 구분</small><input required value={subjects} onChange={e=>setSubjects(e.target.value)}/></label><div className="two-col">{[['question_reward','문제 승인 보상',1,100],['daily_reward_cap','학생별 하루 보상 한도',10,10000],['room_cost','맵 한 칸 비용',1,100],['stat_cost','능력치 성장 기본 비용',1,100],['stat_cap','능력치 상한',20,500],['monster_base','몬스터 기본 제작비',1,100],['effect_base','아이템·기술 기본 제작비',1,100],['npc_cost','NPC 기본 제작비',1,100],['book_cost','책 기본 제작비',1,100],['adventure_daily_cap','탐험 창조력 하루 한도',0,100],['loot_chance','몬스터 아이템 드롭 확률 (%)',0,100],['encounter_chance','이동 중 몬스터 조우 확률 (%)',0,100],['book_reward_chance','독서 창조력 확률 (%)',0,100]].map(([key,name,min,max])=><label key={key}>{name}<input type="number" required min={Number(min)} max={Number(max)} value={s[String(key)]} onChange={e=>setS({...s,[String(key)]:Number(e.target.value)})}/></label>)}</div>{[['registration_open','학생 가입 신청 받기'],['creation_open','창작 신청 받기'],['paused','게임 일시정지']].map(([key,name])=><label className="toggle" key={key}><input type="checkbox" checked={s[key]} onChange={e=>setS({...s,[key]:e.target.checked})}/>{name}</label>)}<button className="primary">운영 설정 저장</button></form></section>;
}

function LedgerList({data}:{data:Snapshot}) {return <>{!data.ledger.length&&<Empty>아직 창조력 내역이 없습니다.</Empty>}{[...data.ledger].sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,50).map(l=><div className="ledger-row" key={l.id}><div><strong>{l.reason}</strong><small>{data.students.find(s=>s.id===l.student)?.nickname} · {new Date(l.created_at).toLocaleString('ko-KR')}</small></div><span>{l.amount>0?'+':''}{l.amount}{l.reserved_delta!==0&&<small>예약 {l.reserved_delta>0?'+':''}{l.reserved_delta}</small>}</span></div>)}</>;}
function Wallet({data,run}:{data:Snapshot;run:Run}) {return <><div className="metrics">{[['사용 가능',data.profile.balance-data.profile.reserved],['예약 중',data.profile.reserved],['총 보유',data.profile.balance]].map(([l,n])=><div className="card metric" key={l}><span>{l}</span><strong>{n}</strong></div>)}</div><section className="card"><h2>나의 능력 성장</h2><div className="three-col">{[['attack','공격력',data.profile.attack],['defense','방어력',data.profile.defense],['max_hp','최대 체력',data.profile.max_hp]].map(([key,name,n])=>{const units=key==='max_hp'?Number(n)/5:Number(n),cost=data.settings.stat_cost*(1+Math.floor(units/20));return <div className="list-card" key={key}><h3>{name} {n}</h3><p>+{key==='max_hp'?5:1} · 비용 {cost}</p><button disabled={units>=data.settings.stat_cap||data.profile.balance-data.profile.reserved<cost} onClick={()=>run(()=>rpc('grow',{p_stat:key,p_request:crypto.randomUUID()}))}>성장하기</button></div>;})}</div></section><section className="card"><h2>창조력 기록</h2><LedgerList data={data}/></section></>;}
