import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { BookOpen, Compass, Hammer, ShieldCheck, Sparkles, Users, LogOut, RefreshCw, Map, Settings as SettingsIcon, ChevronRight } from 'lucide-react';
import { rpc, snapshot, studentAccess, supabase } from './api';
import { categories, defaults, estimate, labels, previewSnapshot, validateQuestion, type Question, type Settings, type Snapshot } from './model';
import './classroom.css';

type Run = (action:()=>Promise<unknown>,message?:string)=>Promise<void>;
const status=(s:string)=><span className={`tag ${s}`}>{labels[s]||s}</span>;
const formData=(e:FormEvent<HTMLFormElement>)=>new FormData(e.currentTarget);
function Check({id,selected,set}:{id:string;selected:string[];set:(v:string[])=>void}) {return <input type="checkbox" aria-label="선택" checked={selected.includes(id)} onChange={e=>set(e.target.checked?[...selected,id]:selected.filter(x=>x!==id))}/>;}
function Empty({children}:{children:ReactNode}) {return <div className="empty">{children}</div>;}

export default function ClassroomApp() {
 const [data,setData]=useState<Snapshot|null>(null),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('home');
 async function refresh(){const next=await snapshot();setData(next);}
 const run:Run=async(action,message='저장했습니다.')=>{if(preview){setNotice('화면 미리보기입니다. 실제 저장과 승인은 Supabase 연결 후 사용할 수 있습니다.');return;}setBusy(true);setError('');setNotice('');try{await action();await refresh();setNotice(message);}catch(e){setError((e as Error).message||'처리하지 못했습니다.');}finally{setBusy(false);}};
 useEffect(()=>{if(!supabase)return;setBusy(true);refresh().catch(e=>setError(e.message)).finally(()=>setBusy(false));const {data:listener}=supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')setData(null);});return()=>listener.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!data||preview)return;const check=()=>{if(document.visibilityState==='visible')refresh().catch(e=>{setData(null);setError(e.message);});};window.addEventListener('focus',check);return()=>window.removeEventListener('focus',check);},[data?.profile.id,preview]);
 const teacher=data?.profile.role==='teacher';
 const menus=teacher?[['home','교실 현황',Compass],['students','학생 관리',Users],['questions','문제 검토',BookOpen],['proposals','창작 검토',Hammer],['world','세계 관리',Map],['settings','운영 설정',SettingsIcon]]:[['home','세계 탐험',Compass],['questions','문제 만들기',BookOpen],['proposals','창작 작업실',Hammer],['wallet','창조력 · 성장',Sparkles]];
 return <div className="classroom">
 <aside className="rail"><div className="brand"><span className="brand-icon">M</span><div>우리 반 MUD<small>LEARN · CREATE · EXPLORE</small></div></div>
 <div className="rail-caption">{data?(teacher?'TEACHER CONSOLE':'CLASSROOM ADVENTURE'):'함께 만드는 배움의 세계'}</div>
 {data&&<nav>{menus.map(([id,name,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/>{name}{id==='questions'&&teacher&&<b>{data.questions.filter(q=>q.status==='submitted').length}</b>}</button>)}</nav>}
 <div className="rail-bottom"><span className="online-dot"/> {preview?'읽기 전용 미리보기':supabase?'학급 전용 공간':'연결 준비 중'}<small>작은 질문이 새로운 세계를 만듭니다.</small></div></aside>
 <main><header className="topbar"><span>{teacher?'교사 관리실':'배움의 모험'}</span><div>{data&&<><span>{data.profile.nickname}</span><button aria-label="새로고침" disabled={busy} onClick={()=>run(async()=>{},'새로고침했습니다.')}><RefreshCw size={16}/></button><button onClick={async()=>{if(!preview)await supabase?.auth.signOut();setPreview(false);setData(null);setTab('home');}}><LogOut size={16}/>나가기</button></>}</div></header>
 <div className="page">{preview&&<div className="banner">미리보기 · 예시 데이터이며 저장하거나 실제 보상을 지급하지 않습니다.</div>}
 {error&&<div role="alert" className="alert">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
 <fieldset disabled={busy} className="workspace">{!data?<Login run={run} onPreview={role=>{setPreview(true);setData(previewSnapshot(role));setError('');setTab('home');}}/>:<>
 <div className="page-heading"><div><span className="eyebrow">{teacher?'함께 자라는 교실':'오늘도 한 칸 더, 새로운 발견'}</span><h1>{menus.find(m=>m[0]===tab)?.[1] as string}</h1><p>{teacher?'검토는 간단하게, 학생들의 창작은 더 넓게.':'문제를 만들고, 창조력을 모아 우리 반의 세계를 넓혀 보세요.'}</p></div><span className="role-badge">{teacher?<ShieldCheck size={18}/>:<Sparkles size={18}/>} {teacher?'교사 관리자':`창조력 ${data.profile.balance-data.profile.reserved}`}</span></div>
 {teacher&&tab==='home'&&<Dashboard data={data} go={setTab}/>}
 {teacher&&tab==='students'&&<Students data={data} run={run}/>}
 {tab==='questions'&&(teacher?<ReviewQuestions data={data} run={run}/>:<Questions data={data} run={run}/>)}
 {tab==='proposals'&&<Proposals data={data} run={run} teacher={!!teacher}/>}
 {teacher&&tab==='world'&&<World data={data} run={run}/>}
 {teacher&&tab==='settings'&&<SettingsForm settings={data.settings} run={run}/>}
 {!teacher&&tab==='home'&&<Adventure data={data} run={run}/>}
 {!teacher&&tab==='wallet'&&<Wallet data={data} run={run}/>}
 </>}</fieldset>{busy&&<div className="working" role="status">처리 중…</div>}</div>
 </main></div>;
}

function Login({run,onPreview}:{run:Run;onPreview:(r:'teacher'|'student')=>void}) {
 const [mode,setMode]=useState('login');
 return <div className="login-layout"><section className="welcome"><span className="eyebrow">OUR CLASS, OUR WORLD</span><h1>질문 하나로<br/>새로운 세계가<br/><em>열립니다.</em></h1><p>문제를 풀고, 친구의 질문을 만나고,<br/>함께 다음 모험을 만들어 보세요.</p><div className="pixel-world">⌂ ── ✦ ── ♜<br/>　　│　　 │<br/>　　♧ ── ◇</div></section><section className="card login-card"><h2>{mode==='teacher'?'교사 관리실':'모험을 시작할까요?'}</h2><p>우리 학급만 사용하는 작은 세계</p><div className="segmented">{[['login','학생 로그인'],['signup','가입 신청'],['teacher','교사']].map(([id,text])=><button key={id} className={mode===id?'chosen':''} onClick={()=>setMode(id)}>{text}</button>)}</div>
 <form onSubmit={e=>{e.preventDefault();const f=formData(e);run(async()=>{if(mode==='teacher'){if(!supabase)throw new Error('Supabase 연결이 필요합니다.');const {error}=await supabase.auth.signInWithPassword({email:String(f.get('name')),password:String(f.get('password'))});if(error)throw error;}else await studentAccess(mode,String(f.get('name')),String(f.get('password')));},mode==='signup'?'가입 신청을 보냈습니다. 선생님 승인 후 로그인해 주세요.':'로그인했습니다.');}}>
 <label>{mode==='teacher'?'교사 이메일':'닉네임'}<input key={mode} name="name" required type={mode==='teacher'?'email':'text'} maxLength={mode==='teacher'?200:20} placeholder={mode==='teacher'?'teacher@example.com':'사용할 닉네임'}/></label>
 <label>{mode==='teacher'?'비밀번호':'PIN 번호'}<input name="password" key={`${mode}-pin`} required type="password" inputMode={mode==='teacher'?'text':'numeric'} pattern={mode==='teacher'?undefined:'[0-9]{6}'} minLength={mode==='teacher'?8:6} maxLength={mode==='teacher'?100:6} placeholder={mode==='teacher'?'교사 비밀번호':'숫자 6자리'}/></label>
 <button className="primary wide" type="submit">{mode==='signup'?'선생님께 가입 신청':'입장하기'}<ChevronRight size={17}/></button></form>
 <small>{mode==='signup'?'선생님이 승인한 뒤 이용할 수 있어요. 이메일은 필요 없어요.':'PIN을 잊었다면 선생님께 초기화를 요청하세요.'}</small>
 <div className="preview-links"><span>연결 전 화면 살펴보기</span><button onClick={()=>onPreview('teacher')}>교사 화면</button><button onClick={()=>onPreview('student')}>학생 화면</button></div></section></div>;
}

function Dashboard({data,go}:{data:Snapshot;go:(t:string)=>void}) {
 const metrics=[['가입 승인 대기',data.students.filter(s=>s.status==='pending').length,'students'],['문제 검토 대기',data.questions.filter(q=>q.status==='submitted').length,'questions'],['창작 승인 대기',data.proposals.filter(p=>p.status==='pending').length,'proposals'],['우리 세계의 장소',data.places.filter(p=>p.active).length,'world']];
 return <><div className="metrics">{metrics.map(([label,n,tab])=><button className="card metric" key={label} onClick={()=>go(String(tab))}><span>{label}</span><strong>{n}<small>개</small></strong><span className="metric-link">살펴보기 →</span></button>)}</div><div className="two-col"><section className="card"><h2>오늘의 검토함</h2><p>질문이 새로운 모험의 시작이 됩니다.</p>{data.questions.filter(q=>q.status==='submitted').slice(0,4).map(q=><button className="review-row" key={q.id} onClick={()=>go('questions')}><span className="subject-icon">{q.subject[0]}</span><div><strong>{q.body}</strong><small>{data.students.find(s=>s.id===q.author)?.nickname} · {q.subject} · {labels[q.kind]}</small></div><ChevronRight size={17}/></button>)}{!data.questions.some(q=>q.status==='submitted')&&<Empty>검토할 문제가 없습니다.</Empty>}</section><section className="card"><h2>세계가 자라고 있어요</h2><MiniMap data={data}/><p>맵 한 칸 {data.settings.room_cost} · 문제 승인 {data.settings.question_reward} 창조력</p><button className="secondary" onClick={()=>go('world')}>전체 세계 관리</button></section></div></>;
}

function Questions({data,run}:{data:Snapshot;run:Run}) {
 const blank=()=>({subject:localStorage.getItem('mud_classroom_last_subject')||data.settings.subjects[0],kind:'ox' as Question['kind'],body:'',options:['','','',''],answer:'O',explanation:''});
 const [q,setQ]=useState(blank),[edit,setEdit]=useState<string|null>(null),[done,setDone]=useState(false);
 useEffect(()=>{if(!data.settings.subjects.includes(q.subject))setQ(v=>({...v,subject:data.settings.subjects[0]}));},[data.settings.subjects.join('|')]);
 function set(field:string,value:any){setDone(false);setQ(v=>({...v,[field]:value}));}
 return <div className="two-col form-columns"><section className="card"><h2>{edit?'문제 수정하기':'내가 만드는 한 문제'}</h2><p>배운 내용을 친구에게 설명해 보세요.</p><form onSubmit={e=>{e.preventDefault();const payload={...q,options:q.kind==='choice'?q.options:[]};run(async()=>{const invalid=validateQuestion(payload);if(invalid)throw new Error(invalid);await rpc('submit_question',{p_id:edit,p_subject:q.subject,p_kind:q.kind,p_body:q.body,p_options:payload.options,p_answer:q.answer,p_explanation:q.explanation});localStorage.setItem('mud_classroom_last_subject',q.subject);setDone(true);setEdit(null);},'선생님께 문제를 제출했습니다.');}}>
 <div className="form-row"><label>과목<select value={q.subject} onChange={e=>{set('subject',e.target.value);localStorage.setItem('mud_classroom_last_subject',e.target.value);}}>{data.settings.subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>문제유형<select value={q.kind} onChange={e=>{const kind=e.target.value as Question['kind'];setQ(v=>({...v,kind,answer:kind==='ox'?'O':kind==='choice'?'1':''}));setDone(false);}}><option value="ox">OX</option><option value="short">단답형</option><option value="choice">객관식 · 4지선다</option></select></label></div>
 <label>문제<textarea required minLength={3} maxLength={2000} rows={4} value={q.body} onChange={e=>set('body',e.target.value)} placeholder="친구에게 어떤 질문을 하고 싶나요?"/></label>
 {q.kind==='choice'&&<div className="choices-input">{q.options.map((o,i)=><label key={i}>보기 {i+1}<input required maxLength={500} value={o} onChange={e=>set('options',q.options.map((x,j)=>i===j?e.target.value:x))}/></label>)}</div>}
 <label>정답{q.kind==='short'?<input required maxLength={200} value={q.answer} onChange={e=>set('answer',e.target.value)} placeholder="짧은 정답 하나"/>:<select value={q.answer} onChange={e=>set('answer',e.target.value)}>{(q.kind==='ox'?['O','X']:['1','2','3','4']).map(a=><option key={a} value={a}>{q.kind==='choice'?`${a}번`:a}</option>)}</select>}</label>
 <label>해설<textarea required maxLength={2000} rows={3} value={q.explanation} onChange={e=>set('explanation',e.target.value)} placeholder="왜 이 답이 맞는지 짧게 설명해 주세요."/></label>
 <button type="submit" className="primary wide" disabled={done}>교사에게 제출</button>{done&&<button type="button" className="secondary wide" onClick={()=>{setQ({...blank(),subject:q.subject});setDone(false);}}>같은 과목으로 다음 문제 만들기</button>}</form></section>
 <section className="card"><h2>내가 보낸 문제</h2><p>최초 승인 시 최대 {data.settings.question_reward} 창조력 · 하루 {data.settings.daily_reward_cap}까지</p>{data.questions.length===0&&<Empty>첫 문제를 만들어 보세요.</Empty>}{data.questions.map(row=><article className="list-card" key={row.id}><div className="row-between">{status(row.status)}<small>{row.subject} · {labels[row.kind]}</small></div><h3>{row.body}</h3>{row.feedback&&<p className="feedback">선생님: {row.feedback}</p>}<button className="text-button" onClick={()=>{setQ({subject:row.subject,kind:row.kind,body:row.body,options:row.kind==='choice'?row.options:['','','',''],answer:row.answer,explanation:row.explanation});setEdit(row.id);setDone(false);}}>수정하기{row.rewarded?' · 추가 보상 없음':''}</button></article>)}</section></div>;
}

function ReviewQuestions({data,run}:{data:Snapshot;run:Run}) {
 const [selected,setSelected]=useState<string[]>([]),[filter,setFilter]=useState('submitted'),[search,setSearch]=useState(''),[feedback,setFeedback]=useState(''),[accepted,setAccepted]=useState<Record<string,string>>({});
 const rows=data.questions.filter(q=>(filter==='all'||q.status===filter)&&`${q.body} ${q.subject} ${data.students.find(s=>s.id===q.author)?.nickname}`.includes(search));
 const eligible=selected.filter(id=>data.questions.some(q=>q.id===id&&q.status==='submitted'));
 const review=(ids:string[],action:string)=>run(async()=>{await rpc('review_questions',{p_ids:ids,p_action:action,p_feedback:feedback,p_accepted:ids.length===1?(accepted[ids[0]]||'').split(',').map(x=>x.trim()).filter(Boolean):[]});setSelected([]);},action==='approved'?'승인과 창조력 지급을 처리했습니다.':'검토 결과를 보냈습니다.');
 return <><div className="toolbar card"><input aria-label="문제 검색" placeholder="문제 · 과목 · 학생 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="검토 상태" value={filter} onChange={e=>{setFilter(e.target.value);setSelected([]);}}>{['submitted','approved','revision','rejected','all'].map(s=><option key={s} value={s}>{labels[s]||'전체'}</option>)}</select><button onClick={()=>setSelected(rows.filter(q=>q.status==='submitted').map(q=>q.id))}>대기 문제 모두 선택</button></div>
 <div className="approval-bar"><span>{eligible.length}개 선택 · 최대 {eligible.filter(id=>!data.questions.find(q=>q.id===id)?.rewarded).length*data.settings.question_reward} 창조력 <small>(학생별 일일 한도 적용)</small></span><button className="primary" disabled={!eligible.length} onClick={()=>review(eligible,'approved')}>선택 승인 + 창조력 지급</button></div>
 <label className="feedback-input">검토 의견<input value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="수정할 내용을 짧게 남겨 주세요."/></label>
 {!rows.length&&<Empty>이 상태의 문제가 없습니다.</Empty>}<div className="review-grid">{rows.map(q=><article className="card question-review" key={q.id}><div className="row-between"><div className="inline"><Check id={q.id} selected={selected} set={setSelected}/><strong>{data.students.find(s=>s.id===q.author)?.nickname}</strong></div>{status(q.status)}</div><div className="chips"><span>{q.subject}</span><span>{labels[q.kind]}</span><span>{q.rewarded?'지급 완료':`최대 +${data.settings.question_reward}`}</span></div><h3>{q.body}</h3>{q.options.map((o,i)=><div key={i} className={q.answer===String(i+1)?'answer correct':'answer'}>{i+1}. {o}</div>)}<div className="answer-key">정답: {q.answer}</div><p className="explanation">{q.explanation}</p>{q.kind==='short'&&<label>추가 인정 정답 <small>쉼표로 구분 · 개별 승인 시 적용</small><input value={accepted[q.id]||''} onChange={e=>setAccepted({...accepted,[q.id]:e.target.value})}/></label>}
 {data.questions.some(other=>other.id!==q.id&&other.body.replace(/\s/g,'')===q.body.replace(/\s/g,''))&&<p className="warning">같은 문장의 문제가 있습니다. 중복 여부를 확인해 주세요.</p>}
 {q.status==='submitted'&&<div className="actions"><button className="primary" onClick={()=>review([q.id],'approved')}>승인 + 창조력 지급</button><button onClick={()=>review([q.id],'revision')}>수정 요청</button><button onClick={()=>review([q.id],'rejected')}>반려</button></div>}{q.status==='approved'&&<button onClick={()=>run(()=>rpc('set_active',{p_kind:'question',p_ids:[q.id],p_active:false}),'출제를 중지했습니다. 기존 보상은 유지됩니다.')}>출제 중지</button>}</article>)}</div></>;
}

function Students({data,run}:{data:Snapshot;run:Run}) {
 const [selected,setSelected]=useState<string[]>([]),[student,setStudent]=useState(''),[amount,setAmount]=useState(10),[reason,setReason]=useState(''),[pin,setPin]=useState('');
 return <><div className="approval-bar"><span>{selected.length}명 선택</span><div className="actions"><button onClick={()=>setSelected(data.students.filter(s=>s.role==='student'&&s.status==='pending').map(s=>s.id))}>대기 학생 선택</button><button className="primary" disabled={!selected.length} onClick={()=>run(()=>rpc('manage_students',{p_ids:selected,p_status:'approved'}),'가입을 승인했습니다.')}>선택 가입 승인</button><button disabled={!selected.length} onClick={()=>run(()=>rpc('manage_students',{p_ids:selected,p_status:'suspended'}),'선택 학생의 이용을 중지했습니다.')}>이용 중지</button></div></div>
 <div className="card table-wrap"><table><thead><tr><th>선택</th><th>닉네임</th><th>상태</th><th>사용 가능</th><th>예약</th><th>레벨</th><th>관리</th></tr></thead><tbody>{data.students.filter(s=>s.role==='student').map(s=><tr key={s.id}><td><Check id={s.id} selected={selected} set={setSelected}/></td><td>{s.nickname}</td><td>{status(s.status)}</td><td>{s.balance-s.reserved}</td><td>{s.reserved}</td><td>{s.level}</td><td><button onClick={()=>setStudent(s.id)}>선택</button></td></tr>)}</tbody></table></div>
 {student&&<section className="card"><h2>{data.students.find(s=>s.id===student)?.nickname} 관리</h2><div className="two-col"><form onSubmit={e=>{e.preventDefault();run(()=>rpc('adjust_balance',{p_student:student,p_amount:amount,p_reason:reason,p_request:crypto.randomUUID()}));}}><label>창조력 조정 <small>차감은 음수 입력</small><input type="number" min={-10000} max={10000} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>사유<input required minLength={2} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary">내역을 남기고 조정</button></form><form onSubmit={e=>{e.preventDefault();run(async()=>{await studentAccess('reset','',pin,student);setPin('');},'새 PIN으로 변경했습니다.');}}><label>새 PIN<input type="password" required pattern="[0-9]{6}" maxLength={6} value={pin} onChange={e=>setPin(e.target.value)}/></label><p>기존 PIN은 조회하지 않습니다.</p><button>PIN 초기화</button></form></div></section>}
 <section className="card"><h2>최근 창조력 내역</h2><LedgerList data={data}/></section></>;
}

function Proposals({data,run,teacher}:{data:Snapshot;run:Run;teacher:boolean}) {
 const [kind,setKind]=useState('map'),[name,setName]=useState(''),[draft,setDraft]=useState<Record<string,any>>({count:1,category:'forest',anchor:data.places[0]?.id,direction:'동',description:'',hp:60,attack:10,defense:2,level:1,min_correct:2,place:'',subject:'',effect:'heal',power:10}),[feedback,setFeedback]=useState('');
 const change=(key:string,value:any)=>setDraft(d=>({...d,[key]:value}));
 const review=(id:string,action:string)=>run(()=>rpc('review_proposal',{p_id:id,p_action:action,p_feedback:feedback}),action==='approved'?'승인한 창작물이 세계에 반영되었습니다.':'신청 상태를 변경하고 예약액을 해제했습니다.');
 return <div className={teacher?'':'two-col form-columns'}>{!teacher&&<section className="card"><h2>새로운 창작</h2><p>신청할 때 비용을 예약하고, 승인되면 사용해요.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await rpc('submit_proposal',{p_id:crypto.randomUUID(),p_kind:kind,p_name:name,p_data:draft});setName('');},'창작물을 신청하고 창조력을 예약했습니다.');}}><div className="form-row"><label>만들 것<select value={kind} onChange={e=>setKind(e.target.value)}>{['map','monster','item','skill'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>이름<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label></div><label>설명<textarea rows={2} maxLength={1000} value={draft.description} onChange={e=>change('description',e.target.value)}/></label>
 {kind==='map'?<><div className="form-row"><label>칸 수<input type="number" min={1} max={10} required value={draft.count} onChange={e=>change('count',Number(e.target.value))}/></label><label>장소 성격<select value={draft.category} onChange={e=>change('category',e.target.value)}>{Object.entries(categories).filter(([k])=>k!=='square').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label>연결할 기존 장소<select required value={draft.anchor} onChange={e=>change('anchor',e.target.value)}>{data.places.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>확장 방향<select value={draft.direction} onChange={e=>change('direction',e.target.value)}>{['동','서','남','북'].map(d=><option key={d}>{d}</option>)}</select></label><small>여러 칸은 선택한 방향으로 이어집니다. 상점·길드·성·제작소·포털은 다음 단계입니다.</small></>:kind==='monster'?<><div className="form-row wrap">{[['hp','체력',10,500],['attack','공격력',1,data.settings.stat_cap],['defense','방어력',0,data.settings.stat_cap],['level','레벨',1,20],['min_correct','최소 정답 횟수',1,5]].map(([key,text,min,max])=><label key={key}>{text}<input required type="number" min={Number(min)} max={Number(max)} value={draft[String(key)]} onChange={e=>change(String(key),Number(e.target.value))}/></label>)}</div><label>배치 장소<select required value={draft.place} onChange={e=>change('place',e.target.value)}><option value="">숲·던전·보스방 선택</option>{data.places.filter(p=>p.active&&['forest','dungeon','boss'].includes(p.category)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>출제 과목<select value={draft.subject} onChange={e=>change('subject',e.target.value)}><option value="">모든 과목</option>{data.settings.subjects.map(s=><option key={s}>{s}</option>)}</select></label></>:<><label>효과<select value={draft.effect} onChange={e=>change('effect',e.target.value)}>{['heal','guard','strike'].map(k=><option value={k} key={k}>{labels[k]}</option>)}</select></label><label>효과 강도<input required type="number" min={1} max={30} value={draft.power} onChange={e=>change('power',Number(e.target.value))}/></label><small>{kind==='item'?'소모품은 한 번 사용하면 사라집니다.':'기본 기술은 매 턴 선택할 수 있습니다.'} 공격·회복은 정답일 때, 방어는 오답 피해에 적용됩니다.</small></>}
 <div className="cost"><span>필요한 창조력</span><strong>{estimate(kind,draft,data.settings)}</strong></div><button className="primary wide" disabled={!data.settings.creation_open}>교사에게 제작 신청</button></form></section>}
 <section><div className="card"><h2>{teacher?'창작 승인 대기함':'내 창작 신청'}</h2>{teacher&&<label>검토 의견<input value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="수정 요청 또는 반려 사유"/></label>}{data.proposals.length===0&&<Empty>아직 신청한 창작물이 없습니다.</Empty>}{data.proposals.map(p=><article className="list-card" key={p.id}><div className="row-between"><span>{labels[p.kind]} · {teacher?data.students.find(s=>s.id===p.author)?.nickname:'내 창작'}</span>{status(p.status)}</div><h3>{p.name}</h3><p>{p.data.description}</p><div className="chips">{p.kind==='map'?<><span>{p.data.count}칸 · {categories[p.data.category]}</span><span>{data.places.find(l=>l.id===p.data.anchor)?.name} → {p.data.direction}</span></>:p.kind==='monster'?<><span>HP {p.data.hp} · ATK {p.data.attack} · DEF {p.data.defense}</span><span>Lv.{p.data.level} · 정답 {p.data.min_correct}회 이상</span></>:<span>{labels[p.data.effect]} +{p.data.power}</span>}<span>창조력 {p.cost}</span></div>{p.feedback&&<p className="feedback">{p.feedback}</p>}{p.status==='pending'&&<div className="actions">{teacher?<><button className="primary" onClick={()=>review(p.id,'approved')}>승인 및 생성</button><button onClick={()=>review(p.id,'revision')}>수정 요청</button><button onClick={()=>review(p.id,'rejected')}>반려</button></>:<button onClick={()=>review(p.id,'cancelled')}>신청 취소 · 예약 해제</button>}</div>}{!teacher&&['revision','rejected','cancelled'].includes(p.status)&&<button onClick={()=>{setKind(p.kind);setName(p.name);setDraft({...draft,...p.data});}}>내용을 복사해 다시 만들기</button>}</article>)}</div></section></div>;
}

function MiniMap({data,onSelect}:{data:Snapshot;onSelect?:(id:string)=>void}) {
 const xs=data.places.map(p=>p.x),ys=data.places.map(p=>p.y),minX=Math.min(0,...xs),minY=Math.min(0,...ys);
 const pos=(id:string)=>{const p=data.places.find(p=>p.id===id);return p?[(p.x-minX)*160+95,(p.y-minY)*110+55]:[0,0];};
 return <div className="map-scroll"><svg role="img" aria-label="우리 반 공동 세계 지도" width={Math.max(500,(Math.max(0,...xs)-minX+1)*160+30)} height={Math.max(220,(Math.max(0,...ys)-minY+1)*110+30)}>{data.links.map(l=>{const a=pos(l.source),b=pos(l.target);return <line key={`${l.source}-${l.direction}`} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke="#9aada6" strokeWidth="2"/>;})}{data.places.map(p=>{const [x,y]=pos(p.id);return <g key={p.id} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={p.name} onClick={()=>onSelect?.(p.id)} onKeyDown={e=>{if(e.key==='Enter')onSelect?.(p.id);}} style={{cursor:onSelect?'pointer':'default'}} opacity={p.active?1:.4}><rect x={x-68} y={y-30} width="136" height="64" rx="12" fill={p.category==='square'?'#245e4b':'#fff'} stroke="#b5c8bd"/><text x={x} y={y-5} textAnchor="middle" fill={p.category==='square'?'#fff':'#263d34'} fontSize="12">{p.name.length>11?p.name.slice(0,10)+'…':p.name}</text><text x={x} y={y+15} textAnchor="middle" fill={p.category==='square'?'#d0e7d9':'#70847a'} fontSize="10">{categories[p.category]}</text></g>;})}</svg></div>;
}

function World({data,run}:{data:Snapshot;run:Run}) {
 const [kind,setKind]=useState('place'),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[place,setPlace]=useState('');
 const rows=(kind==='place'?data.places:data.entities.filter(e=>e.kind===kind)).filter(e=>e.name.includes(search));
 return <><section className="card"><div className="row-between"><h2>공동 세계 지도</h2><small>장소를 누르면 상세 정보를 볼 수 있습니다.</small></div><MiniMap data={data} onSelect={setPlace}/>{place&&<div className="feedback"><strong>{data.places.find(p=>p.id===place)?.name}</strong><p>{data.places.find(p=>p.id===place)?.description}</p><small>출구: {data.links.filter(l=>l.source===place).map(l=>`${l.direction} → ${data.places.find(p=>p.id===l.target)?.name}`).join(' / ')||'없음'}</small></div>}</section>
 <div className="toolbar card"><select aria-label="콘텐츠 종류" value={kind} onChange={e=>{setKind(e.target.value);setSelected([]);}}><option value="place">전체 맵</option>{['monster','item','skill'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select><input placeholder="이름 검색" aria-label="콘텐츠 검색" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>setSelected(rows.map(r=>r.id))}>전체 선택</button><button disabled={!selected.length} onClick={()=>run(()=>rpc('set_active',{p_kind:kind,p_ids:selected,p_active:true}))}>활성화</button><button disabled={!selected.length} onClick={()=>run(()=>rpc('set_active',{p_kind:kind,p_ids:selected,p_active:false}),'비활성화했습니다. 해당 장소의 학생은 광장으로 이동합니다.')}>비활성화</button></div>
 <div className="card table-wrap"><table><thead><tr><th>선택</th><th>이름</th><th>종류 / 능력</th><th>제작자</th><th>상태</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><Check id={r.id} selected={selected} set={setSelected}/></td><td>{r.name}</td><td>{r.category?categories[r.category]:r.kind==='monster'?`HP ${r.data.hp} / ATK ${r.data.attack} / DEF ${r.data.defense}`:`${labels[r.data.effect]} +${r.data.power}`}</td><td>{data.students.find(s=>s.id===r.creator)?.nickname||'교사'}</td><td>{r.active?'활성':'중지'}</td></tr>)}</tbody></table>{rows.length===0&&<Empty>등록된 콘텐츠가 없습니다.</Empty>}</div>
 {selected.length>0&&<ContentEditor kind={kind} ids={selected} data={data} run={run}/>}</>;
}

function ContentEditor({kind,ids,data,run}:{kind:string;ids:string[];data:Snapshot;run:Run}) {
 const [field,setField]=useState('name'),[value,setValue]=useState('');
 useEffect(()=>{setField(ids.length===1?'name':kind==='place'?'description':kind==='monster'?'attack':'power');setValue('');},[kind,ids.join(',')]);
 const fields:Record<string,string>={...(ids.length===1?{name:'이름'}:{}),description:'설명',...(kind==='place'?{category:'장소 성격'}:kind==='monster'?{hp:'체력',attack:'공격력',defense:'방어력',level:'레벨',min_correct:'최소 정답 횟수',place:'배치 장소'}:{power:'효과 강도',effect:'효과'})};
 return <section className="card"><h2>선택한 {ids.length}개 편집</h2><p>수정할 항목 하나를 선택해 적용합니다. 진행 중인 전투는 시작 당시 능력치를 유지합니다.</p><form onSubmit={e=>{e.preventDefault();run(()=>rpc('edit_content',{p_kind:kind,p_ids:ids,p_patch:{[field]:['hp','attack','defense','level','min_correct','power'].includes(field)?Number(value):value}}));}}><div className="form-row"><label>수정할 항목<select value={field} onChange={e=>{setField(e.target.value);setValue('');}}>{Object.entries(fields).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>변경할 값{['category','place','effect'].includes(field)?<select required value={value} onChange={e=>setValue(e.target.value)}><option value="">선택하세요</option>{(field==='category'?Object.entries(categories):field==='place'?data.places.filter(p=>p.active&&['forest','dungeon','boss'].includes(p.category)).map(p=>[p.id,p.name]):['heal','guard','strike'].map(k=>[k,labels[k]])).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>:<input required value={value} onChange={e=>setValue(e.target.value)} type={['hp','attack','defense','level','min_correct','power'].includes(field)?'number':'text'}/>}</label></div><button className="primary">선택 항목에 적용</button></form></section>;
}

function SettingsForm({settings,run}:{settings:Settings;run:Run}) {
 const [s,setS]=useState(settings),[subjects,setSubjects]=useState(settings.subjects.join(', '));
 return <section className="card settings-card"><h2>수업에 맞게 바꾸세요</h2><p>새 규칙은 다음 신청부터 적용됩니다. 이미 예약한 제작 비용은 유지합니다.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{if(!supabase)throw new Error('연결이 필요합니다.');const {error}=await supabase.from('mud_settings').update({...s,subjects:[...new Set(subjects.split(',').map(x=>x.trim()).filter(Boolean))]}).eq('id',true);if(error)throw error;});}}><label>과목 목록 <small>쉼표로 구분</small><input required value={subjects} onChange={e=>setSubjects(e.target.value)}/></label><div className="two-col">{[['question_reward','문제 승인 보상',1,100],['daily_reward_cap','학생별 하루 보상 한도',10,10000],['room_cost','맵 한 칸 비용',1,100],['stat_cost','능력치 성장 기본 비용',1,100],['stat_cap','능력치 상한',20,500],['monster_base','몬스터 기본 제작비',1,100],['effect_base','아이템·기술 기본 제작비',1,100]].map(([key,name,min,max])=><label key={key}>{name}<input type="number" required min={Number(min)} max={Number(max)} value={s[String(key)]} onChange={e=>setS({...s,[String(key)]:Number(e.target.value)})}/></label>)}</div>{[['registration_open','학생 가입 신청 받기'],['creation_open','창작 신청 받기'],['paused','게임 일시정지']].map(([key,name])=><label className="toggle" key={key}><input type="checkbox" checked={s[key]} onChange={e=>setS({...s,[key]:e.target.checked})}/>{name}</label>)}<button className="primary">운영 설정 저장</button></form></section>;
}

function Adventure({data,run}:{data:Snapshot;run:Run}) {
 const [lines,setLines]=useState(['[SYSTEM] 우리 반 데이터 세계에 접속했습니다.','도움말: 동 / 서 / 남 / 북 / 봐라 / 공격 / 회복 / 후퇴']),[command,setCommand]=useState(''),[answer,setAnswer]=useState(''),[effect,setEffect]=useState('');
 const loc=data.places.find(p=>p.id===data.profile.location),battle=data.battle,monster=data.entities.find(e=>e.id===battle?.monster);
 const write=(line:string)=>setLines(v=>[...v.slice(-150),line]);
 const act=(cmd:string)=>run(async()=>{write(`> ${cmd}`);if(cmd==='공격')await rpc('start_battle');else if(cmd==='후퇴'){await rpc('escape');write('안전하게 전투에서 물러났습니다.');}else if(cmd==='도움말'){write('동 / 서 / 남 / 북 / 봐라 / 공격 / 회복 / 후퇴');}else if(['동','서','남','북','봐라','회복'].includes(cmd))write(await rpc('world_action',{p_command:cmd}));else throw new Error('도움말에 있는 명령을 입력해 주세요.');},'');
 return <div className="adventure-grid"><section className="terminal"><div className="terminal-title"><span>● ● ●</span> CLASSROOM / {loc?.name}</div><div className="terminal-stats">Lv.{data.profile.level} · HP {data.profile.hp}/{data.profile.max_hp} · ATK {data.profile.attack} · DEF {data.profile.defense}</div><h2>⌂ {loc?.name}</h2><p>{loc?.description}</p><div className="terminal-lines" aria-live="polite">{lines.map((l,i)=><div key={i}>{l}</div>)}</div>{battle&&<div className="battle"><div className="row-between"><strong>⚔ {monster?.name||'몬스터'}</strong><span>HP {battle.hp} · 정답 {battle.correct_count}회</span></div><small>{battle.question.subject} · {labels[battle.question.kind]}{battle.repeated?' · 문제 수가 부족해 복습 문제입니다.':''}</small><h3>{battle.question.body}</h3><form onSubmit={e=>{e.preventDefault();run(async()=>{const result=await rpc('answer',{p_token:battle.token,p_answer:answer,p_effect:effect||null});write(`${result.correct?'정답!':'다시 생각해 봐요.'} 피해 ${result.damage} / 받은 피해 ${result.taken}\n${result.explanation}${result.status==='won'?'\n몬스터 처치! 경험치 +'+result.exp:result.status==='lost'?'\n광장으로 돌아와 체력을 회복했습니다.':''}`);setAnswer('');},'');}}>{battle.question.kind==='short'?<input aria-label="단답형 정답" required value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="정답 입력"/>:<div className="battle-choices">{(battle.question.kind==='ox'?['O','X']:battle.question.options).map((o,i)=>{const value=battle.question.kind==='ox'?o:String(i+1);return <label key={i}><input type="radio" name="battle-answer" required checked={answer===value} onChange={()=>setAnswer(value)}/>{battle.question.kind==='choice'?`${i+1}. `:''}{o}</label>;})}</div>}<select aria-label="사용할 기술 또는 아이템" value={effect} onChange={e=>setEffect(e.target.value)}><option value="">기본 공격</option>{data.entities.filter(e=>e.creator===data.profile.id&&e.active&&e.kind!=='monster').map(e=><option key={e.id} value={e.id}>{e.name} · {labels[e.data.effect]} +{e.data.power}{e.kind==='item'?' (1회 소모)':''}</option>)}</select><button className="primary" type="submit">정답 제출 · 행동 실행</button></form></div>}
 <form className="command" onSubmit={e=>{e.preventDefault();act(command.trim());setCommand('');}}><span>❯</span><input aria-label="터미널 명령" value={command} onChange={e=>setCommand(e.target.value)} placeholder="명령어를 입력하세요"/><button>입력</button></form></section><aside><section className="card"><h2>빠른 행동</h2><div className="direction-pad">{['북','서','동','남'].map(d=><button disabled={!!battle} key={d} onClick={()=>act(d)}>{d}</button>)}</div><div className="actions"><button onClick={()=>act('봐라')}>둘러보기</button><button disabled={!!battle} onClick={()=>act('공격')}>공격</button><button disabled={!!battle} onClick={()=>act('회복')}>회복</button><button disabled={!battle} onClick={()=>act('후퇴')}>후퇴</button></div></section><section className="card"><h2>연결된 길</h2>{data.links.filter(l=>l.source===data.profile.location).map(l=><p key={l.direction}>{l.direction} → {data.places.find(p=>p.id===l.target)?.name||'닫힌 장소'}</p>)}</section><section className="card"><h2>모험의 약속</h2><p>정답을 맞히면 공격합니다. 강한 몬스터는 여러 번 생각하고 도전해야 해요.</p><p>승인된 문제가 없으면 전투를 시작할 수 없습니다.</p></section></aside></div>;
}
function LedgerList({data}:{data:Snapshot}) {return <>{!data.ledger.length&&<Empty>아직 창조력 내역이 없습니다.</Empty>}{[...data.ledger].sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,50).map(l=><div className="ledger-row" key={l.id}><div><strong>{l.reason}</strong><small>{data.students.find(s=>s.id===l.student)?.nickname} · {new Date(l.created_at).toLocaleString('ko-KR')}</small></div><span>{l.amount>0?'+':''}{l.amount}{l.reserved_delta!==0&&<small>예약 {l.reserved_delta>0?'+':''}{l.reserved_delta}</small>}</span></div>)}</>;}
function Wallet({data,run}:{data:Snapshot;run:Run}) {return <><div className="metrics">{[['사용 가능',data.profile.balance-data.profile.reserved],['예약 중',data.profile.reserved],['총 보유',data.profile.balance]].map(([l,n])=><div className="card metric" key={l}><span>{l}</span><strong>{n}</strong></div>)}</div><section className="card"><h2>나의 능력 성장</h2><div className="three-col">{[['attack','공격력',data.profile.attack],['defense','방어력',data.profile.defense],['max_hp','최대 체력',data.profile.max_hp]].map(([key,name,n])=>{const units=key==='max_hp'?Number(n)/5:Number(n),cost=data.settings.stat_cost*(1+Math.floor(units/20));return <div className="list-card" key={key}><h3>{name} {n}</h3><p>+{key==='max_hp'?5:1} · 비용 {cost}</p><button disabled={units>=data.settings.stat_cap||data.profile.balance-data.profile.reserved<cost} onClick={()=>run(()=>rpc('grow',{p_stat:key,p_request:crypto.randomUUID()}))}>성장하기</button></div>;})}</div></section><section className="card"><h2>창조력 기록</h2><LedgerList data={data}/></section></>;}
