import {useState} from 'react';
import {rpc} from './api';
import {labels,type Snapshot,type Blacksmith} from './model';
import {hasPrerequisites} from './creationRules';
import {enhancementRecipes,enhancedData} from './enhancement';
type Run=(action:()=>Promise<unknown>,message?:string)=>Promise<void>;
type Choice={kind:'item'|'skill';id:string;name:string;level:number;data:Record<string,any>};
const summary=(d:Record<string,any>)=>`공격 ${d.attack||0} · 방어 ${d.defense||0} · 체력 ${d.hp||0} · ${labels[d.effect]||'효과'} ${d.power||0}`;
export default function Enhancements({data,run,teacher=false}:{data:Snapshot;run:Run;teacher?:boolean}) {
 const [id,setId]=useState(()=>crypto.randomUUID()),[name,setName]=useState('강화사'),[place,setPlace]=useState(data.places.find(p=>p.active)?.id||''),[description,setDescription]=useState('강화의 돌로 장비와 기술을 강화해 줄게. 결과와 비용을 먼저 확인하렴.'),[active,setActive]=useState(true);
 const [smithId,setSmithId]=useState(''),[confirm,setConfirm]=useState<(Choice&{request:string;smith:string})|null>(null),[result,setResult]=useState('');
 const smiths=data.blacksmiths.filter(s=>s.active&&s.place===data.profile.location),smith=smiths.find(s=>s.id===smithId)||smiths[0];
 const edit=(s?:Blacksmith)=>{setId(s?.id||crypto.randomUUID());setName(s?.name||'강화사');setPlace(s?.place||data.places.find(p=>p.active)?.id||'');setDescription(s?.description||'장비와 기술의 강화 비용을 먼저 확인하렴.');setActive(s?.active??true);};
 if(teacher)return <section className="card"><div className="row-between"><h2>강화사 배치</h2><button onClick={()=>edit()}>새 강화사</button></div><p>강화사는 이 장소에 고정 배치됩니다. 학생은 해당 장소에서 ‘강화’ 명령으로 만납니다.</p><div className="actions">{data.blacksmiths.map(s=><button key={s.id} onClick={()=>edit(s)}>{s.name} · {data.places.find(p=>p.id===s.place)?.name} · {s.active?'운영 중':'중지'}</button>)}</div><form onSubmit={event=>{event.preventDefault();run(()=>rpc('save_blacksmith',{p_id:id,p_name:name,p_place:place,p_description:description,p_active:active}),'강화사 배치를 저장했습니다.');}}><div className="form-row"><label>강화사 이름<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>배치 장소<select required value={place} onChange={e=>setPlace(e.target.value)}>{data.places.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><label>대화 내용<textarea required maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="toggle"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>운영 중</label><button className="primary">강화사 저장</button></form></section>;
 const targets:Choice[]=[...data.inventory.filter(i=>i.student===data.profile.id&&i.slot!=='consumable').map(i=>({kind:'item' as const,id:i.id,name:i.name,level:i.enhancement||0,data:i.data})),...data.learned_skills.filter(k=>k.student===data.profile.id).flatMap(k=>{const e=data.entities.find(e=>e.id===k.skill&&e.active);return e?[{kind:'skill' as const,id:e.id,name:e.name,level:k.enhancement||0,data:e.data}]:[];})];
 return <div><p>강화의 돌 <strong>{data.profile.enhancement_stones||0}개</strong> · 사용 가능 창조력 {data.profile.balance-data.profile.reserved}</p><p>돌은 몬스터 승리 시 35% 확률로 획득합니다. Lv.1~4는 1개, Lv.5~9는 1~2개, Lv.10~19는 1~3개, Lv.20 이상은 2~4개입니다. 하루 획득 한도는 {data.settings.stone_daily_cap??20}개입니다.</p><p>최대 +9 · 양수 기본 수치가 단계당 5% 증가합니다(소수점 버림). 음수 핸디캡은 유지합니다. 실패해도 파괴되지 않으며, 돌과 표시된 창조력은 소모됩니다. 실패 시 50% 확률로 1단계 하락합니다.</p>{result&&<p role="status" className="notice">{result}</p>}
 {data.battle?<p>전투를 마친 뒤 강화사를 만나세요.</p>:!smith?<p>현재 장소에 운영 중인 강화사가 없습니다. 교사가 세계 관리에서 배치한 장소로 이동하세요.</p>:<><label>만날 강화사<select value={smith.id} onChange={e=>{setSmithId(e.target.value);setConfirm(null);}}>{smiths.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><p className="feedback" style={{whiteSpace:'pre-wrap'}}>{smith.name}: 「{smith.description}」</p>
 {confirm&&<section className="list-card" role="alertdialog" aria-label="강화 시도 확인"><h3>{confirm.name} +{confirm.level} → +{confirm.level+1}</h3><p>돌 {enhancementRecipes[confirm.level].stones}개 · 창조력 {enhancementRecipes[confirm.level].creativity} · 성공률 {enhancementRecipes[confirm.level].chance}%</p><p>실패해도 위 재료와 창조력은 소모됩니다. 실패 시 50% 확률로 +{Math.max(0,confirm.level-1)}로 내려갑니다. 아이템과 기술은 사라지지 않습니다.</p><div className="actions"><button onClick={()=>setConfirm(null)}>취소</button><button className="primary" onClick={()=>run(async()=>{const r=await rpc('enhance',{p_blacksmith:confirm.smith,p_kind:confirm.kind,p_target:confirm.id,p_expected_level:confirm.level,p_request:confirm.request});setResult(r.text);setConfirm(null);},'')}>확인 · 강화 시도</button></div></section>}
 <div className="shop-catalog">{targets.map(c=>{const recipe=enhancementRecipes[c.level],ready=hasPrerequisites(c.data,data),afford=recipe&&(data.profile.enhancement_stones||0)>=recipe.stones&&data.profile.balance-data.profile.reserved>=recipe.creativity;return <article className="list-card" key={c.kind+c.id}><strong>{c.name} +{c.level} · {labels[c.kind]}</strong><p>현재: {summary(enhancedData(c.data,c.level))}</p>{recipe&&<><p>성공 후: {summary(enhancedData(c.data,c.level+1))}</p><p>돌 {recipe.stones}개 · 창조력 {recipe.creativity} · 성공 {recipe.chance}%</p></>}<button disabled={!!confirm||!recipe||!ready||!afford} onClick={()=>{setResult('');setConfirm({...c,request:crypto.randomUUID(),smith:smith.id});}}>{!recipe?'최대 강화':!ready?'선행 조건 미충족':!afford?'재료 또는 창조력 부족':'강화 확인'}</button></article>;})}</div>{!targets.length&&<p>보유한 장비나 습득한 기술이 없습니다.</p>}</>}
 <details><summary>단계별 비용과 성공률</summary><table><thead><tr><th>도전 단계</th><th>돌</th><th>창조력</th><th>성공률</th></tr></thead><tbody>{enhancementRecipes.map((r,n)=><tr key={n}><td>+{n+1}</td><td>{r.stones}</td><td>{r.creativity}</td><td>{r.chance}%</td></tr>)}</tbody></table><p>기본 수치가 작으면 소수점 버림으로 다음 단계의 정수 수치가 같을 수 있습니다. 강화는 매입가를 올리지 않습니다.</p></details></div>;
}
