import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {categories,START,type Snapshot} from './model';

export default function WorldMap({data,onSelect,focusId='',focusVersion=0}:{data:Snapshot;onSelect?:(id:string)=>void;focusId?:string;focusVersion?:number}){
 const viewport=useRef<HTMLDivElement>(null),[size,setSize]=useState({w:800,h:480}),[zoom,setZoom]=useState<number|null>(null),[search,setSearch]=useState(''),[chosen,setChosen]=useState(''),[navigation,setNavigation]=useState(0);
 const move=useRef<{x:number;y:number}|null>(null),drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 const roots=data.places.filter(p=>!p.village_id),minX=Math.min(0,...roots.map(p=>p.x)),minY=Math.min(0,...roots.map(p=>p.y));
 const width=Math.max(520,(Math.max(0,...roots.map(p=>p.x))-minX+1)*200+40),height=Math.max(240,(Math.max(0,...roots.map(p=>p.y))-minY+1)*140+40);
 const fitted=Math.min(1,size.w/width,size.h/height),scale=zoom??fitted;
 const point=(id:string)=>{let p=data.places.find(p=>p.id===id);if(p?.village_id)p=data.places.find(v=>v.id===p!.village_id);return {x:((p?.x??0)-minX)*200+120,y:((p?.y??0)-minY)*140+90};};
 const center=(id:string)=>{if(!data.places.some(p=>p.id===id))return;const p=point(id);move.current=p;setZoom(z=>Math.max(z??fitted,1));setChosen(id);setNavigation(n=>n+1);onSelect?.(id);};
 useEffect(()=>{const el=viewport.current;if(!el)return;const o=new ResizeObserver(()=>setSize({w:el.clientWidth,h:el.clientHeight}));o.observe(el);return()=>o.disconnect();},[]);
 useEffect(()=>{if(focusId)center(focusId);},[focusId,focusVersion]);
 useLayoutEffect(()=>{const el=viewport.current,p=move.current;if(el&&p){el.scrollLeft=p.x*scale-el.clientWidth/2;el.scrollTop=p.y*scale-el.clientHeight/2;move.current=null;}},[scale,chosen,navigation,focusVersion]);
 const changeZoom=(next:number)=>{const el=viewport.current;if(el)move.current={x:(el.scrollLeft+el.clientWidth/2)/scale,y:(el.scrollTop+el.clientHeight/2)/scale};setZoom(Math.max(Math.min(fitted,.1),Math.min(2,next)));};
 const hits=search.trim()?data.places.filter(p=>p.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).sort((a,b)=>a.name.localeCompare(b.name,'ko')):[];
 const selected=data.places.find(p=>p.id===chosen);
 return <div className="world-map"><div className="map-tools"><form onSubmit={e=>{e.preventDefault();if(hits.length===1)center(hits[0].id);}}><input aria-label="세계 지도 검색" placeholder="장소·건물 이름 검색" value={search} onChange={e=>setSearch(e.target.value)}/><button type="submit" disabled={hits.length!==1}>위치 찾기</button></form><div className="actions"><button type="button" aria-label="지도 축소" onClick={()=>changeZoom(scale/1.4)}>−</button><span>{Math.round(scale*100)}%</span><button type="button" aria-label="지도 확대" onClick={()=>changeZoom(scale*1.4)}>＋</button><button type="button" onClick={()=>{move.current=null;setZoom(null);viewport.current?.scrollTo(0,0);}}>전체 보기</button><button type="button" onClick={()=>center(START)}>시작 광장</button></div></div>
 {search.trim()&&<div className="map-results" aria-label="지도 검색 결과">{hits.length?hits.map(p=><button type="button" key={p.id} onClick={()=>center(p.id)}>{p.name} · {categories[p.category]}{p.village_id?` / ${data.places.find(v=>v.id===p.village_id)?.name||'소속 마을'}`:''}{!p.active?' · 중지':''}</button>):<p>일치하는 장소가 없습니다.</p>}</div>}
 <p className="map-guide">장소를 누르면 확대합니다. 빈 공간을 드래그하거나 스크롤바로 이동하세요. 건물 이름을 눌러 상세를 확인할 수 있습니다.</p>
 <div className="world-map-viewport" ref={viewport} aria-label="확대 가능한 세계 지도" tabIndex={0} onPointerDown={e=>{if(e.button!==0||(e.target as Element).closest('[data-place]'))return;const el=viewport.current!;drag.current={x:e.clientX,y:e.clientY,left:el.scrollLeft,top:el.scrollTop};el.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current,el=viewport.current;if(d&&el){el.scrollLeft=d.left-e.clientX+d.x;el.scrollTop=d.top-e.clientY+d.y;}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <svg width={Math.max(size.w,width*scale)} height={Math.max(size.h,height*scale)} aria-label="우리 반 공동 세계 지도"><g transform={`scale(${scale})`}>
 {data.links.filter(l=>roots.some(p=>p.id===l.source)&&roots.some(p=>p.id===l.target)).map(l=>{const a=point(l.source),b=point(l.target);return <line key={l.source+l.direction} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#95aaa5" strokeWidth={2}/>;})}
 {roots.map(p=>{const a=point(p.id),children=data.places.filter(b=>b.village_id===p.id).sort((a,b)=>Number(b.id===chosen)-Number(a.id===chosen)||Number(b.active)-Number(a.active)),active=chosen===p.id||selected?.village_id===p.id;return <g key={p.id} transform={`translate(${a.x},${a.y})`} opacity={p.active?1:.5}><g data-place={p.id} role="button" tabIndex={0} aria-label={`지도 ${p.name}`} onClick={()=>center(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();center(p.id);}}}><title>{p.name} · {categories[p.category]}</title><rect x={-85} y={-43} width={170} height={86} rx={10} fill={active?'#e0f3eb':'#fff'} stroke={active?'#17644e':'#a6bab3'} strokeWidth={active?3:1}/><text textAnchor="middle" y={-17} fontSize={13} fill="#193d34">{p.name.length>12?p.name.slice(0,11)+'…':p.name}</text><text textAnchor="middle" y={3} fontSize={10} fill="#56736a">{categories[p.category]}{!p.active?' · 중지':''}</text></g>
 {children.slice(0,1).map(b=><g key={b.id} data-place={b.id} role="button" tabIndex={0} aria-label={`건물 ${b.name}`} onClick={()=>center(b.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();center(b.id);}}}><title>{b.name}{!b.active?' · 중지':''}</title><rect x={-78} y={11} width={156} height={25} rx={4} fill={b.id===chosen?'#bedfd0':'#eef3f0'}/><text textAnchor="middle" y={28} fontSize={10} fill="#245546">{b.name.length>13?b.name.slice(0,12)+'…':b.name}{!b.active?' (중지)':''}</text></g>)}</g>;})}
 </g></svg></div>
 {selected&&<div className="map-selection" role="status"><strong>{selected.name}</strong> · {categories[selected.category]}{selected.village_id&&<> / 소속 마을: <button type="button" onClick={()=>center(selected.village_id!)}>{data.places.find(p=>p.id===selected.village_id)?.name}</button></>}<p>{selected.description}</p>{!selected.village_id&&<p>출구: {data.links.filter(l=>l.source===selected.id).map(l=>`${l.direction} → ${data.places.find(p=>p.id===l.target)?.name||'연결 장소'}`).join(' / ')||'연결된 길 없음'}</p>}{data.places.filter(p=>p.village_id===(selected.village_id||selected.id)).map(p=><button type="button" key={p.id} onClick={()=>center(p.id)}>{p.name}{!p.active?' · 중지':''}</button>)}</div>}
 </div>;
}
